apiVersion: v1
kind: Namespace
metadata:
  name: pplog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pplog-apigateway-service
  namespace: pplog
  labels:
    app: pplog-apigateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pplog-apigateway-service
  template:
    metadata:
      labels:
        app: pplog-apigateway-service
    spec:
      containers:
      - name: pplog-apigateway-service
        image: kim6562166086/pplog-apigateway-service:latest  # Gateway 서비스 Docker 이미지
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: pplog-apigateway-service
  namespace: pplog
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000  # 외부에서 접근할 NodePort
  selector:
    app: pplog-apigateway-service
