apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.deployment.name }}
